import pkg from '/opt/node22/lib/node_modules/playwright/index.js';
const { chromium } = pkg;
const browser = await chromium.launch();
const page = await (await browser.newContext({viewport:{width:1440,height:900}})).newPage();
const errs=[]; page.on('pageerror', e=>errs.push(e.message)); page.on('dialog',d=>d.accept());
const click=(t)=>page.evaluate(x=>{const b=[...document.querySelectorAll('button')].find(e=>e.textContent.includes(x));b&&b.click();},t);
await page.goto('http://localhost:4173/',{waitUntil:'domcontentloaded', timeout:20000});
await click('จัดการข้อมูล'); await page.waitForTimeout(300);
await click('โหลดข้อมูลตัวอย่าง'); await page.waitForTimeout(600);
await click('แดชบอร์ด'); await page.waitForTimeout(500);
const revBefore = await page.evaluate(()=>document.body.innerText.match(/รายได้รวม[\s\S]{0,40}/)?.[0]?.replace(/\n/g,' '));
const salesBefore = await page.evaluate(()=>JSON.parse(localStorage.getItem('ptr_sales_v1')||'[]').length);
console.log('BEFORE delete -> sales in storage:', salesBefore, '| dashboard rev:', revBefore);
// go clear sales
await click('นำเข้ายอดขาย'); await page.waitForTimeout(400);
await page.evaluate(()=>{const b=[...document.querySelectorAll('button')].find(e=>e.textContent.includes('ล้างยอดขาย'));b&&b.click();});
await page.waitForTimeout(600);
const salesAfter = await page.evaluate(()=>JSON.parse(localStorage.getItem('ptr_sales_v1')||'[]').length);
await click('แดชบอร์ด'); await page.waitForTimeout(600);
const revAfter = await page.evaluate(()=>document.body.innerText.match(/รายได้รวม[\s\S]{0,40}/)?.[0]?.replace(/\n/g,' '));
const stillSettle = await page.evaluate(()=>document.body.innerText.includes('กระทบยอดจากไฟล์ Settlement'));
console.log('AFTER delete -> sales in storage:', salesAfter, '| dashboard rev:', revAfter);
console.log('settlement panel still shown:', stillSettle);
console.log('errors:', errs.length?[...new Set(errs)].join('|'):'none');
await browser.close();
