import pkg from '/opt/node22/lib/node_modules/playwright/index.js';
const { chromium } = pkg;
const browser = await chromium.launch();
const page = await (await browser.newContext({viewport:{width:1440,height:900}})).newPage();
const errs=[]; page.on('pageerror', e=>errs.push(e.message)); page.on('dialog',d=>d.accept());
await page.goto('http://localhost:4173/',{waitUntil:'domcontentloaded', timeout:20000});
await page.evaluate(()=>{const b=[...document.querySelectorAll('button')].find(e=>e.textContent.includes('รายจ่ายทั่วไป'));b&&b.click();});
await page.waitForTimeout(400);
const addTab=()=>page.evaluate(()=>{const b=[...document.querySelectorAll('button')].find(e=>e.textContent.trim()==='เพิ่มแท็บ');b&&b.click();});
await addTab(); await page.waitForTimeout(150); await addTab(); await page.waitForTimeout(200);
const urls=await page.$$('input[placeholder="วางลิงก์แท็บ Google Sheet"]');
await urls[0].fill('http://localhost:4173/_jun.csv');
await urls[1].fill('http://localhost:4173/_jul.csv');
await page.evaluate(()=>{const b=[...document.querySelectorAll('button')].find(e=>e.textContent.trim()==='ซิงก์ทั้งหมด');b&&b.click();});
await page.waitForTimeout(1500);
const exp=await page.evaluate(()=>JSON.parse(localStorage.getItem('ptr_expenses_v1')||'[]'));
console.log('synced:', exp.length, '| total:', exp.reduce((a,e)=>a+e.amount,0));
console.log('months:', JSON.stringify([...new Set(exp.map(e=>e.month))].sort()));
console.log('sample dates:', JSON.stringify(exp.slice(0,2).map(e=>({date:e.date,month:e.month}))));
console.log('errors:', errs.length?[...new Set(errs)].join('|'):'none');
await browser.close();
